package shoonya.application.entity

import java.time.{LocalDate, ZonedDateTime}

sealed trait Field

case class Text(
                 id: Id,
                 name: Option[String] = None,
                 required: Boolean = false,
                 default: Option[String] = None,
                 maxLength: Int = 255,
                 minLength: Int = 0,
                 possibleValues: Option[List[String]] = None
               ) extends Field

case class Number(
                 id: Id,
                 name: Option[String] = None,
                 required: Boolean = false,
                 default: Option[BigInt] = None,
                 minValue: Option[BigInt] = None,
                 maxValue: Option[BigInt] = None,
                 localeIdentifier: Option[LocaleIdentifier] = None,
                 possibleValues: Option[List[BigInt]] = None
               ) extends Field

case class Decimal(
                   id: Id,
                   name: Option[String] = None,
                   required: Boolean = false,
                   precision: Int = 2,
                   default: Option[BigDecimal] = None,
                   minValue: Option[BigDecimal] = None,
                   maxValue: Option[BigDecimal] = None,
                   localeIdentifier: Option[LocaleIdentifier] = None
                 ) extends Field

/**
 * // Formatting Currency
 * Currency currentCurrency = Currency.getInstance(currentLocale)
 * NumberFormat currencyFormatter = NumberFormat.getCurrencyInstance(currentLocale)
 * currencyFormatter.format(currencyAmount)
 */
case class Currency(
                    id: Id,
                    currencyCode: String, // ISO 4217 code - See https://www2.1010data.com/documentationcenter/beta/1010dataReferenceManual/DataTypesAndFormats/currencyUnitCodes.html
                    name: Option[String] = None,
                    required: Boolean = false,
                    precision: Int = 2,
                    default: Option[BigDecimal] = None,
                    minValue: Option[BigDecimal] = None,
                    maxValue: Option[BigDecimal] = None,
                    localeIdentifier: Option[LocaleIdentifier] = None
                  ) extends Field

case class DateValue(
                   id: Id,
                   name: Option[String] = None,
                   required: Boolean = false,
                   default: Option[LocalDate] = None,
                   minValue: Option[LocalDate] = None,
                   maxValue: Option[LocalDate] = None,
                   localeIdentifier: Option[LocaleIdentifier] = None
                 ) extends Field

case class DateTimeValue(
                          id: Id,
                          name: Option[String] = None,
                          required: Boolean = false,
                          default: Option[ZonedDateTime] = None,
                          minValue: Option[ZonedDateTime] = None,
                          maxValue: Option[ZonedDateTime] = None,
                          localeIdentifier: Option[LocaleIdentifier] = None
                    ) extends Field

case class Email(
                  id: Id,
                  name: Option[String] = None,
                  required: Boolean = false,
                  default: Option[String] = None,
                  possibleValues: Option[List[String]] = None
                ) extends Field

case class Url(
                id: Id,
                name: Option[String] = None,
                required: Boolean = false,
                default: Option[String] = None,
                possibleValues: Option[List[String]] = None
              ) extends Field

case class BooleanValue(
                id: Id,
                name: Option[String] = None,
                required: Boolean = false,
                default: Option[String] = None
              ) extends Field

case class AutoIncrementNumber(
                                id: Id,
                                name: Option[String] = None,
                                required: Boolean = true,
                                startValue: Int = 1,
                                incrementBy: Int = 1,
                                minValue: Option[BigInt] = None,
                                maxValue: Option[BigInt] = None,
                                localeIdentifier: Option[LocaleIdentifier] = None
                              ) extends Field

case class AutoGeneratedText(
                              id: Id,
                              name: Option[String] = None,
                              required: Boolean = true,
                              prefix: Option[String] = Option("AUTO"),
                              startValue: Int = 1,
                              incrementBy: Int = 1,
                              maxLength: Int = 255,
                              minLength: Int = 0
                            ) extends Field

case class ValueList(
                                  id: Id,
                                  field: Field,
                                  name: Option[String] = None,
                                  required: Boolean = false
                                ) extends Field

case class ValueMap(
                     id: Id,
                     fields: List[Field],
                     name: Option[String] = None,
                     required: Boolean = false
                   ) extends Field
